# Generated by Django 4.2.4 on 2023-08-29 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TROW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_of_trow', models.CharField(choices=[('heads', 'heads'), ('tails', 'tails')], max_length=7)),
                ('trow_time', models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 29, 20, 9, 32, 755901))),
            ],
        ),
    ]
